"""
Helper to refresh NSE cookies from a browser session.

Option 1 (Manual – easiest):
1. Open https://www.nseindia.com/option-chain in Chrome/Firefox.
2. Open DevTools → Network tab.
3. Refresh the page. Click any request to nseindia.com.
4. Right-click the request → Copy → Copy as cURL (bash).
5. Paste it into a text editor and extract the 'Cookie: ...' value.
6. Save that value into a file named cookies_raw.txt in this folder.
7. Run: python refresh_cookies.py

Option 2 (Browser cookie export extension):
1. Install "Get cookies.txt LOCALLY" extension in Chrome/Firefox.
2. Go to https://www.nseindia.com/option-chain
3. Click the extension → Export cookies.txt
4. Save it as cookies.txt in this folder (overwrite the old one).
"""
import os
import re

RAW_FILE = "cookies_raw.txt"
COOKIE_FILE = "cookies.txt"


def parse_raw_cookie_string(cookie_str: str):
    """Convert a raw 'name=value; name2=value2' string into Netscape cookies.txt lines."""
    cookies = []
    for part in cookie_str.split(";"):
        part = part.strip()
        if "=" not in part:
            continue
        name, value = part.split("=", 1)
        cookies.append((name.strip(), value.strip()))
    return cookies


def build_netscape_cookie_lines(cookie_pairs):
    lines = [
        "# Netscape HTTP Cookie File",
        "# https://curl.se/docs/http-cookies.html",
        "# This file was generated by refresh_cookies.py",
        "",
    ]
    for name, value in cookie_pairs:
        # Netscape format: domain  flag  path  secure  expiry  name  value
        # Using a far-future expiry (2030)
        lines.append(
            f"\t.nseindia.com\tTRUE\t/\tTRUE\t1893456000\t{name}\t{value}"
        )
    return "\n".join(lines)


def main():
    if not os.path.exists(RAW_FILE):
        print(f"{RAW_FILE} not found.")
        print(__doc__)
        return

    raw = open(RAW_FILE).read().strip()
    pairs = parse_raw_cookie_string(raw)
    if not pairs:
        print("No cookie pairs found in the raw file.")
        return

    netscape = build_netscape_cookie_lines(pairs)
    with open(COOKIE_FILE, "w") as f:
        f.write(netscape)
    print(f"Saved {len(pairs)} cookies to {COOKIE_FILE}. Restart the app to use them.")


if __name__ == "__main__":
    main()
